imports:
    - { resource: parameters.yml }
    - { resource: assetic.yml    }
    - { resource: locales.yml   }
    - { resource: security.yml   }

parameters:
    locale:   en #default locale

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        admin: %admin%

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            gedmo_loggable:
                type: annotation
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                is_bundle: false
            FOSMessageBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport:  %mailer_transport%
    host:       %mailer_host%
    username:   %mailer_user%
    password:   %mailer_password%
    encryption: ssl
    auth_mode:  login
    spool:      { type: memory }

services:
 twig.extension.text:
     class: Twig_Extensions_Extension_Text
     tags:
         - { name: twig.extension }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Bricks\UserBundle\Entity\User

    from_email:
        address:        contact@symfonybricks.com
        sender_name:    SymfonyBricks.com

    service:
        mailer: fos_user.mailer.twig_swift

    registration:
        confirmation:
            enabled:    true
            template:   BricksUserBundle:Registration:registration.email.twig

    resetting:
        email:
            template:   BricksUserBundle:Resetting:resetting.email.twig

    profile:
        form:
            type: bricks_user_profile

stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            timestampable: true
            sluggable: true
            loggable: true
    
knp_disqus:
    api_key: WVvKRRE3fnk8HDSq4foXmBo5pr3KPTmaWsa3QyC8LpYOroTfeuL6AAItlw4n3ehg

fos_message:
    db_driver: orm
    thread_class: Bricks\MessageBundle\Entity\Thread
    message_class: Bricks\MessageBundle\Entity\Message
    new_thread_form:
        type: message_bundle.new_thread_form.type.default
    reply_form:
        type: message_bundle.reply_message_form.type.default

presta_sitemap:
    dumper_base_url: "https://symfonybricks.com/"

vich_uploader:
    db_driver: orm
    storage: vich_uploader.storage.filesystem
    mappings:
        user_profile_image:
            uri_prefix: /uploads/users
            upload_destination: %kernel.root_dir%/../web/uploads/users
            delete_on_remove: true
            delete_on_update: true
            namer: bricks.namer_uniqid

avalanche_imagine:
    source_root:  %kernel.root_dir%/../web
    web_root:     %kernel.root_dir%/../web
    cache_prefix: media_cache
    driver:       gd
    filters:
        user_profile_small_thumb:
            type:    thumbnail
            options: { size: [26, 26], mode: inset }