services:

    # Brick Twig extenxion
    bricks.twig.brick_extension:
        class: Bricks\SiteBundle\Extension\BrickExtension
        arguments: [@router, @twig]
        tags:
           - { name: twig.extension }

    # Custom exception listener
    kernel.listener.bricks_exception_lstener:
        class: Bricks\SiteBundle\Listener\ExceptionListener
        arguments: [@templating, @kernel]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }