services:

    # Brick Twig extenxion
    bricks.twig.brick_extension:
        class: Bricks\SiteBundle\Extension\BrickExtension
        arguments: [@router, @twig]
        tags:
           - { name: twig.extension }

    # Custom exception listener
    kernel.listener.bricks_exception_lstener:
        class: Bricks\SiteBundle\Listener\ExceptionListener
        arguments: [@templating, @kernel]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    bricks.sitemap.listener:
        class: Bricks\SiteBundle\Listener\SitemapListener
        arguments: [@router, @doctrine.orm.entity_manager, %interface_translation_locales%]
        tags:
            - { name: presta.sitemap.listener }

    # custom file namer
    bricks.namer_uniqid:
        class: Bricks\SiteBundle\Namer\BricksNamer