services:

    # Brick Twig extenxion
    bricks.twig.brick_extension:
        class: Bricks\SiteBundle\Extension\BrickExtension
        arguments: [@router, @twig]
        tags:
           - { name: twig.extension }
           